# Generated by Django 5.0.7 on 2024-08-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vercel_deploy', '0002_timetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
